version: "3"

services:
  flask:
    build: ./python
#    ports:
#     - 5000:80
    depends_on:
      - redis
    links:
      - redis
    networks:
      - backend

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  nginx_static:
    build: ./nginx-static
    volumes:
      - ./nginx-static/html/:/var/www/html/static/
      - ./nginx-static/configurations/:/etc/nginx/conf.d/
    restart: always
    networks:
      - backend

  nginx_proxy:
    build: ./nginx-proxy
    volumes:
      - ./nginx-proxy/configurations/:/etc/nginx/conf.d/
    restart: always
    links:
      - nginx_static
      - flask
    ports:
      - 80:80
    networks:
      - backend

networks:
  backend: